### ISSUE TITLE
Human visual response option in Pcond set incorrectly.

### ISSUE THREAD

**Issue by built-tools** [ladybug-tools/honeybee-radiance-command#213]
https://github.com/ladybug-tools/honeybee-radiance-command/blob/master/honeybee_radiance_command/options/pcond.py#L73-L85

Almost certain that this is a bug, as there is no way that self.h.value will mean anything. Should be self._h.value instead. I am not sure if this option in Pcond is being used anywhere for the time being. Just making a note here to fix it later. Not a priority for now.

**Comment by mostaphaRoudsari** [comment]
Hi @built-tools! I would push a quick fix for this one.

@chriswmackey, should know if we are using this option.

**Comment by mostaphaRoudsari** [comment]
I just did push a fix so it shouldn't be an issue anymore: https://github.com/ladybug-tools/honeybee-radiance-command/pull/214
