### ISSUE TITLE
Parsing options from a string does not result in proper assignment in case of joined options.

### ISSUE THREAD

**Issue by built-tools** [ladybug-tools/honeybee-radiance-command#222]
If the option contains a [joined string option](https://github.com/ladybug-tools/honeybee-radiance-command/pull/220/files#diff-0973a4345df42d5e309a419d40ee4e379e5bd32ce19c827ac33dfd8445622270R19-R21) like the case below,
```
def test_from_string():
    options=RmtxopOptions()
    options.update_from_string('-fa -v')
    assert options.v==True
    assert options.f=='a'
```
The final test  `assert options.f=='a'` fails. I guess this is [because the parsing is not refined enough to figure out which options are string joined](https://github.com/ladybug-tools/honeybee-radiance-command/blob/master/honeybee_radiance_command/cutil.py#L21-L50).

**Comment by built-tools** [comment]
Update: I guess this can be fixed if one [overrides the method from the OptionsCollection class](https://github.com/ladybug-tools/honeybee-radiance-command/blob/master/honeybee_radiance_command/options/optionbase.py#L433-L465). Haven't done that yet because I am wondering if this problem exists in other classes as well.

**Comment by mostaphaRoudsari** [comment]
Interesting! It actually tries to work with joined cases too: https://github.com/ladybug-tools/honeybee-radiance-command/blob/231de913d0ad2f743bf0f169d3104a98bcee7f50/honeybee_radiance_command/options/optionbase.py#L445-L452
