### ISSUE TITLE
Rfluxmtx and (possibly) rcontrib do not allow the setting of multiprocessing option in certain cases

### ISSUE THREAD

**Issue by built-tools** [ladybug-tools/honeybee-radiance-command#229]
The error is this:
![image](https://user-images.githubusercontent.com/91887472/148694338-29b4c796-b4d5-4f36-9c6c-c9c070584958.png)

This is what I am trying to do:
![image](https://user-images.githubusercontent.com/91887472/148694392-cbe84a7f-c11c-40bd-958d-57dc286c8c88.png)
The reason to do this is to redirect the rfluxmtx output to multiple matrices at the same time while tracing rays one. So, this is a pretty useful option. 

I think the reason why this is raising exceptions is that we are relying on the [on_setattr method inherited from rtrace](https://github.com/ladybug-tools/honeybee-radiance-command/blob/master/honeybee_radiance_command/options/rtrace.py#L121-L124).

**Comment by built-tools** [comment]
The solution will be to override/reimplement the rtrace [setattr method in rcontrib](https://github.com/ladybug-tools/honeybee-radiance-command/blob/858df588e8dd4c07121b88aac4cdfe6154b58664/honeybee_radiance_command/options/rcontrib.py#L50-L74). 
Except for (i or I), most of the conditional tests that are being run for rtrace are not relevant for rcontrib anyway as the ambient caching parameters are not applicable for rcontrib.

**Comment by mostaphaRoudsari** [comment]
Hi @built-tools! Yes. This is on me and the error here is based on the rtrace documentation assuming the `-o` here is for `-ospec`.

![image](https://user-images.githubusercontent.com/2915573/149024735-b7ea10c0-320d-4506-93a0-993dd6c98694.png)

![image](https://user-images.githubusercontent.com/2915573/149024829-83f9e300-6fcf-4df0-acc7-23ee99cdd8db.png)

Here is the code that is raising the error:

https://github.com/ladybug-tools/honeybee-radiance-command/blob/858df588e8dd4c07121b88aac4cdfe6154b58664/honeybee_radiance_command/options/rtrace.py#L121-L124

I like the idea of re-writing the one for rcontrib - another solution is to do a check for the class name using `self.__class__.__name__` and only remove the unrelevant checks when the name is not RtraceOptions.

**Comment by built-tools** [comment]
This was addressed by https://github.com/ladybug-tools/honeybee-radiance-command/pull/230
